import React, { useState, useRef, useEffect } from 'react';
import { Play, Pause, Film, Edit3, Type, Music, BookOpen, Check, Sparkles, Upload } from 'lucide-react';
import StoryboardModal from './StoryboardModal';
import LyricsEditorModal from './LyricsEditorModal';
import AutoGeneratorModal from './AutoGeneratorModal';
import { copyToNotebookClipboard } from './NotebookExporter';

const LyricsEnginePlayer = ({ trackData: initialTrackData, apiBaseUrl = 'https://lyrics-engine-backend-1.onrender.com' }) => {
  const [trackData, setTrackData] = useState(initialTrackData);
  const [storyboardData, setStoryboardData] = useState(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [fontStyle, setFontStyle] = useState('sans');
  
  // Modal State Controls
  const [isStoryboardOpen, setIsStoryboardOpen] = useState(false);
  const [isEditorOpen, setIsEditorOpen] = useState(false);
  const [isAutoGrabOpen, setIsAutoGrabOpen] = useState(false);
  const [copiedNotebook, setCopiedNotebook] = useState(false);

  const audioRef = useRef(null);
  const activeLyricRef = useRef(null);
  const fileInputRef = useRef(null);

  useEffect(() => {
    if (initialTrackData) {
      setTrackData(initialTrackData);
    }
  }, [initialTrackData]);

  const togglePlayPause = () => {
    if (!audioRef.current || !audioRef.current.src) return;
    if (isPlaying) {
      audioRef.current.pause();
    } else {
      audioRef.current.play().catch(e => console.warn("Audio play blocked or missing:", e));
    }
    setIsPlaying(!isPlaying);
  };

  const handleTimeUpdate = () => {
    if (audioRef.current) {
      setCurrentTime(audioRef.current.currentTime);
    }
  };

  const handleLoadedMetadata = () => {
    if (audioRef.current) {
      setDuration(audioRef.current.duration);
    }
  };

  const handleSeek = (e) => {
    const newTime = parseFloat(e.target.value);
    setCurrentTime(newTime);
    if (audioRef.current) {
      audioRef.current.currentTime = newTime;
    }
  };

  const handleAudioFileUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const customAudioUrl = URL.createObjectURL(file);
      setTrackData((prev) => ({ ...prev, audioUrl: customAudioUrl }));
      setIsPlaying(false);
      setCurrentTime(0);
    }
  };

  const getCurrentLyricIndex = () => {
    if (!trackData?.lyrics || trackData.lyrics.length === 0) return -1;
    let index = -1;
    for (let i = 0; i < trackData.lyrics.length; i++) {
      if (currentTime >= trackData.lyrics[i].startTime) {
        index = i;
      } else {
        break;
      }
    }
    return index;
  };

  const currentLyricIdx = getCurrentLyricIndex();

  useEffect(() => {
    if (activeLyricRef.current) {
      activeLyricRef.current.scrollIntoView({
        behavior: 'smooth',
        block: 'center'
      });
    }
  }, [currentLyricIdx]);

  const handleSaveFormattedLyrics = (newLyrics) => {
    setTrackData((prev) => ({ ...prev, lyrics: newLyrics }));
  };

  const handleSongAutoGenerated = (generatedData) => {
    setTrackData({
      trackId: Date.now().toString(),
      title: generatedData.title,
      artist: generatedData.artist,
      audioUrl: generatedData.audioUrl || "",
      lyrics: generatedData.lyrics || []
    });
    if (generatedData.storyboard) {
      setStoryboardData(generatedData.storyboard);
    }
    setIsPlaying(false);
    setCurrentTime(0);
  };

  const handleExportToNotebook = async () => {
    const success = await copyToNotebookClipboard(trackData, storyboardData);
    if (success) {
      setCopiedNotebook(true);
      setTimeout(() => setCopiedNotebook(false), 2500);
    }
  };

  const fontClass = fontStyle === 'cambria' ? 'font-serif' : 'font-sans';

  return (
    <div className={`min-h-screen bg-slate-950 text-slate-100 flex flex-col justify-between ${fontClass}`}>
      
      {/* Header Bar */}
      <header className="flex flex-wrap items-center justify-between p-4 bg-slate-900/80 border-b border-slate-800 backdrop-blur-md gap-3 z-10">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-amber-400/10 rounded-lg text-amber-400">
            <Music size={22} />
          </div>
          <div>
            <h1 className="text-base font-bold text-amber-400 leading-tight">
              {trackData?.title || "Karaoke & Songs Appreciation"}
            </h1>
            <p className="text-xs text-slate-400">
              {trackData?.artist || "William H Chan Studio"}
            </p>
          </div>
        </div>

        {/* Control Toolbar */}
        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={() => setIsAutoGrabOpen(true)}
            className="flex items-center gap-1.5 bg-amber-400 hover:bg-amber-300 text-slate-950 px-3.5 py-1.5 rounded-lg text-xs font-bold transition shadow-lg shadow-amber-400/20 cursor-pointer"
          >
            <Sparkles size={15} />
            <span>Start Auto-Grab</span>
          </button>

          <input
            type="file"
            ref={fileInputRef}
            onChange={handleAudioFileUpload}
            accept="audio/*"
            className="hidden"
          />
          <button
            onClick={() => fileInputRef.current?.click()}
            className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-700 transition cursor-pointer"
          >
            <Upload size={14} className="text-amber-400" />
            <span>Load MP3</span>
          </button>

          <div className="flex items-center gap-1.5 bg-slate-800 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-300">
            <Type size={14} className="text-amber-400" />
            <select
              value={fontStyle}
              onChange={(e) => setFontStyle(e.target.value)}
              className="bg-transparent text-xs text-slate-200 focus:outline-none cursor-pointer"
            >
              <option value="sans" className="bg-slate-900 text-slate-200">Sans-Serif (Modern)</option>
              <option value="cambria" className="bg-slate-900 text-slate-200">Cambria (Classic Serif)</option>
            </select>
          </div>

          <button
            onClick={() => setIsEditorOpen(true)}
            className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-700 transition cursor-pointer"
          >
            <Edit3 size={14} className="text-amber-400" />
            <span>Edit Lyrics</span>
          </button>

          <button
            onClick={() => setIsStoryboardOpen(true)}
            className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-700 transition cursor-pointer"
          >
            <Film size={14} className="text-amber-400" />
            <span>AI Storyboard</span>
          </button>

          <button
            onClick={handleExportToNotebook}
            className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-700 transition cursor-pointer"
          >
            {copiedNotebook ? <Check size={14} className="text-emerald-400" /> : <BookOpen size={14} className="text-amber-400" />}
            <span>{copiedNotebook ? 'Copied!' : 'Export Notebook'}</span>
          </button>
        </div>
      </header>

      {/* Main Lyrics Display */}
      <main className="flex-1 flex flex-col items-center justify-center p-6 text-center overflow-hidden relative">
        {!trackData?.lyrics || trackData.lyrics.length === 0 ? (
          <div className="flex flex-col items-center space-y-3 text-slate-500">
            <Music size={40} className="stroke-1 opacity-50" />
            <p className="text-sm">No lyrics loaded for this track.</p>
          </div>
        ) : (
          <div className="w-full max-w-2xl h-[50vh] overflow-y-auto space-y-6 py-20 no-scrollbar">
            {trackData.lyrics.map((line, idx) => {
              const isActive = idx === currentLyricIdx;
              return (
                <p
                  key={idx}
                  ref={isActive ? activeLyricRef : null}
                  className={`text-lg md:text-2xl font-semibold transition-all duration-300 px-4 ${
                    isActive
                      ? 'text-amber-400 scale-105 opacity-100 drop-shadow-[0_2px_8px_rgba(251,191,36,0.2)]'
                      : 'text-slate-500 opacity-40 hover:opacity-70'
                  }`}
                >
                  {line.text}
                </p>
              );
            })}
          </div>
        )}
      </main>

      {/* Audio Player Footer */}
      <footer className="bg-slate-900 border-t border-slate-800 p-4 space-y-4 z-10">
        <audio
          ref={audioRef}
          src={trackData?.audioUrl || ""}
          onTimeUpdate={handleTimeUpdate}
          onLoadedMetadata={handleLoadedMetadata}
          onEnded={() => setIsPlaying(false)}
        />

        {/* Custom Progress Slider */}
        <div className="max-w-3xl mx-auto flex items-center gap-4">
          <span className="text-xs font-mono text-slate-400 w-12 text-right">
            {Math.floor(currentTime / 60)}:{(Math.floor(currentTime % 60) || 0).toString().padStart(2, '0')}
          </span>

          <input
            type="range"
            min="0"
            max={duration || 100}
            value={currentTime || 0}
            onChange={handleSeek}
            className="flex-1 h-2 appearance-none bg-slate-800 rounded-full outline-none [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-amber-400 cursor-pointer"
          />

          <span className="text-xs font-mono text-slate-400 w-12">
            {Math.floor((duration || 0) / 60)}:{(Math.floor((duration || 0) % 60) || 0).toString().padStart(2, '0')}
          </span>
        </div>

        {/* Play Controls */}
        <div className="flex items-center justify-center">
          <button
            onClick={togglePlayPause}
            disabled={!trackData?.audioUrl}
            className="p-3 bg-amber-400 hover:bg-amber-300 disabled:bg-slate-800 disabled:text-slate-600 text-slate-950 rounded-full transition shadow-lg shadow-amber-400/20 active:scale-95 cursor-pointer flex items-center justify-center"
          >
            {isPlaying ? <Pause size={20} /> : <Play size={20} className="ml-0.5" />}
          </button>
        </div>
      </footer>

      <AutoGeneratorModal isOpen={isAutoGrabOpen} onClose={() => setIsAutoGrabOpen(false)} onSongGenerated={handleSongAutoGenerated} apiBaseUrl={apiBaseUrl} />
      <StoryboardModal trackData={trackData} isOpen={isStoryboardOpen} onClose={() => setIsStoryboardOpen(false)} onStoryboardGenerated={(data) => setStoryboardData(data)} apiBaseUrl={apiBaseUrl} />
      <LyricsEditorModal trackData={trackData} isOpen={isEditorOpen} onClose={() => setIsEditorOpen(false)} onSaveLyrics={handleSaveFormattedLyrics} apiBaseUrl={apiBaseUrl} />
    </div>
  );
};

export default LyricsEnginePlayer;
