// src/LyricsEnginePlayer.jsx
import React, { useState, useRef, useEffect, useCallback } from 'react';
import { Play, Pause, Film, Edit3, Type, Music, BookOpen, Check, Sparkles, RotateCcw } from 'lucide-react';
import StoryboardModal from './StoryboardModal';
import LyricsEditorModal from './LyricsEditorModal';
import AutoGeneratorModal from './AutoGeneratorModal';
import { copyToNotebookClipboard } from './NotebookExporter';

const LyricsEnginePlayer = ({ 
  trackData: initialTrackData, 
  apiBaseUrl = '' 
}) => {
  const [trackData, setTrackData] = useState(initialTrackData);
  const [storyboardData, setStoryboardData] = useState(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [fontStyle, setFontStyle] = useState('sans');
  
  // Modal State Controls
  const [isStoryboardOpen, setIsStoryboardOpen] = useState(false);
  const [isEditorOpen, setIsEditorOpen] = useState(false);
  const [isAutoGrabOpen, setIsAutoGrabOpen] = useState(false);
  const [copiedNotebook, setCopiedNotebook] = useState(false);

  const scrollContainerRef = useRef(null);
  const activeLyricRef = useRef(null);
  const virtualTimerRef = useRef(null);

  useEffect(() => {
    if (initialTrackData) {
      setTrackData(initialTrackData);
    }
  }, [initialTrackData]);

  // High-Precision Virtual Metronome Clock (Decoupled from local audio files)
  const togglePlayPause = () => {
    if (isPlaying) {
      if (virtualTimerRef.current) {
        clearInterval(virtualTimerRef.current);
      }
      setIsPlaying(false);
    } else {
      const tickRate = 50; // ms interval for smooth 20fps timeline scrub
      virtualTimerRef.current = setInterval(() => {
        setCurrentTime((prev) => {
          const maxDur = duration || 240;
          const next = prev + tickRate / 1000;
          if (next >= maxDur) {
            clearInterval(virtualTimerRef.current);
            setIsPlaying(false);
            return 0;
          }
          return next;
        });
      }, tickRate);
      setIsPlaying(true);
    }
  };

  const handleResetTimeline = () => {
    if (virtualTimerRef.current) clearInterval(virtualTimerRef.current);
    setIsPlaying(false);
    setCurrentTime(0);
  };

  // Virtual clock cleanup on unmount
  useEffect(() => {
    return () => {
      if (virtualTimerRef.current) clearInterval(virtualTimerRef.current);
    };
  }, []);

  const handleSeek = (timeInSec) => {
    setCurrentTime(timeInSec);
  };

  // Synchronizer: Finds active lyric line index by timestamp
  const getCurrentLyricIndex = useCallback(() => {
    if (!trackData?.lyrics || trackData.lyrics.length === 0) return -1;
    let index = -1;
    for (let i = 0; i < trackData.lyrics.length; i++) {
      const lineStart = trackData.lyrics[i].startTime;
      if (currentTime >= lineStart) {
        index = i;
      } else {
        break;
      }
    }
    return index;
  }, [currentTime, trackData?.lyrics]);

  const currentLyricIdx = getCurrentLyricIndex();

  // Auto-Center Active Lyric with smooth vertical scrolling
  useEffect(() => {
    if (activeLyricRef.current) {
      activeLyricRef.current.scrollIntoView({
        behavior: 'smooth',
        block: 'center'
      });
    }
  }, [currentLyricIdx]);

  const handleSaveFormattedLyrics = (newLyrics) => {
    setTrackData((prev) => ({ ...prev, lyrics: newLyrics }));
  };

  // Ingests Auto-Grabbed payload & normalizes schema for timeline & storyboard
  const handleSongAutoGenerated = (generatedData) => {
    if (virtualTimerRef.current) clearInterval(virtualTimerRef.current);

    const rawLines = generatedData.lines || generatedData.lyrics || [];

    const normalizedLyrics = rawLines.map((line, idx) => {
      const startTimeSec = typeof line.startTime === 'number' 
        ? line.startTime 
        : (line.startTimeMs ? line.startTimeMs / 1000 : idx * 3.5);

      const endTimeSec = typeof line.endTime === 'number' 
        ? line.endTime 
        : (line.endTimeMs ? line.endTimeMs / 1000 : (idx + 1) * 3.5);

      return {
        lineIndex: idx,
        startTime: startTimeSec,
        endTime: endTimeSec,
        text: line.text || line.originalText || '',
        tokens: line.tokens || []
      };
    });

    // Determine duration based on metadata or final lyric timestamp
    let calculatedDuration = generatedData.duration || 0;
    if (!calculatedDuration && normalizedLyrics.length > 0) {
      calculatedDuration = normalizedLyrics[normalizedLyrics.length - 1].endTime + 5;
    }

    setDuration(calculatedDuration);
    setTrackData({
      trackId: generatedData.trackId || Date.now().toString(),
      title: generatedData.title || "Untitled Track",
      artist: generatedData.artist || "Unknown Artist",
      lyrics: normalizedLyrics
    });

    if (generatedData.storyboard) {
      setStoryboardData(generatedData.storyboard);
    }

    setIsPlaying(false);
    setCurrentTime(0);
  };

  const handleExportToNotebook = async () => {
    const success = await copyToNotebookClipboard(trackData, storyboardData);
    if (success) {
      setCopiedNotebook(true);
      setTimeout(() => setCopiedNotebook(false), 2500);
    }
  };

  const fontClass = fontStyle === 'cambria' ? 'font-serif' : 'font-sans';

  return (
    <div className={`h-screen w-screen bg-slate-950 text-slate-100 flex flex-col justify-between overflow-hidden ${fontClass}`}>
      
      {/* Header Toolbar */}
      <header className="flex flex-wrap items-center justify-between p-4 bg-slate-900/90 border-b border-slate-800 backdrop-blur-md gap-3 z-20">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-amber-400/10 rounded-lg text-amber-400">
            <Music size={22} />
          </div>
          <div>
            <h1 className="text-base font-bold text-amber-400 leading-tight">
              {trackData?.title || "Karaoke & Songs Appreciation"}
            </h1>
            <p className="text-xs text-slate-400">
              {trackData?.artist || "William H Chan Studio"}
            </p>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={() => setIsAutoGrabOpen(true)}
            className="flex items-center gap-1.5 bg-amber-400 hover:bg-amber-300 text-slate-950 px-3.5 py-1.5 rounded-lg text-xs font-bold transition shadow-lg shadow-amber-400/20 cursor-pointer"
          >
            <Sparkles size={15} />
            <span>Start Auto-Grab</span>
          </button>

          <button
            onClick={() => setIsStoryboardOpen(true)}
            className="flex items-center gap-1.5 bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/30 px-3.5 py-1.5 rounded-lg text-xs font-bold transition cursor-pointer"
          >
            <Film size={15} />
            <span>AI Storyboard & Prompts</span>
          </button>

          <div className="flex items-center gap-1.5 bg-slate-800 border border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-300">
            <Type size={14} className="text-amber-400" />
            <select
              value={fontStyle}
              onChange={(e) => setFontStyle(e.target.value)}
              className="bg-transparent text-xs text-slate-200 focus:outline-none cursor-pointer"
            >
              <option value="sans" className="bg-slate-900 text-slate-200">Sans-Serif (Modern)</option>
              <option value="cambria" className="bg-slate-900 text-slate-200">Cambria (Classic Serif)</option>
            </select>
          </div>

          <button
            onClick={() => setIsEditorOpen(true)}
            className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-700 transition cursor-pointer"
          >
            <Edit3 size={14} className="text-amber-400" />
            <span>Edit Lyrics</span>
          </button>

          <button
            onClick={handleExportToNotebook}
            className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-700 transition cursor-pointer"
          >
            {copiedNotebook ? <Check size={14} className="text-emerald-400" /> : <BookOpen size={14} className="text-amber-400" />}
            <span>{copiedNotebook ? 'Copied!' : 'Export Notebook'}</span>
          </button>
        </div>
      </header>

      {/* Main High-Contrast Scrollable Lyrics Stage */}
      <main className="flex-1 flex flex-col items-center justify-center p-4 relative overflow-hidden">
        {!trackData?.lyrics || trackData.lyrics.length === 0 ? (
          <div className="flex flex-col items-center space-y-3 text-slate-500">
            <Music size={48} className="stroke-1 opacity-40" />
            <p className="text-sm">No lyrics loaded. Click "Start Auto-Grab" to fetch track metadata.</p>
          </div>
        ) : (
          <div 
            ref={scrollContainerRef}
            className="w-full max-w-3xl h-[58vh] overflow-y-auto space-y-6 py-28 px-4 text-center scroll-smooth scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent"
          >
            {trackData.lyrics.map((line, idx) => {
              const isActive = idx === currentLyricIdx;
              return (
                <div
                  key={idx}
                  ref={isActive ? activeLyricRef : null}
                  onClick={() => handleSeek(line.startTime)}
                  title={`Click to jump to ${(line.startTime).toFixed(1)}s`}
                  className={`cursor-pointer transition-all duration-300 py-3 px-6 rounded-2xl flex flex-wrap justify-center items-center gap-x-2 gap-y-1 ${
                    isActive
                      ? 'text-amber-400 scale-110 font-bold bg-slate-900/90 border border-amber-400/30 shadow-[0_0_25px_rgba(251,191,36,0.15)] opacity-100'
                      : 'text-slate-300 hover:text-slate-100 hover:bg-slate-900/40 opacity-70 hover:opacity-100'
                  }`}
                >
                  {/* Word / Token-Level Rendering with Phonetics */}
                  {line.tokens && line.tokens.length > 0 ? (
                    line.tokens.map((token, tIdx) => (
                      <ruby key={tIdx} className="text-lg md:text-2xl inline-flex flex-col items-center">
                        <span className="leading-tight">{token.char}</span>
                        {token.phonetic && (
                          <rt className="text-[10px] md:text-xs text-amber-300/80 font-normal tracking-wide">
                            {token.phonetic}
                          </rt>
                        )}
                      </ruby>
                    ))
                  ) : (
                    <span className="text-lg md:text-2xl font-medium leading-relaxed">
                      {line.text}
                    </span>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </main>

      {/* Footer Metronome & Scrubber */}
      <footer className="bg-slate-900/95 border-t border-slate-800 p-4 space-y-3 z-20 backdrop-blur-md">
        {/* Scrub Bar */}
        <div className="max-w-3xl mx-auto flex items-center gap-4">
          <span className="text-xs font-mono text-slate-300 w-12 text-right">
            {Math.floor(currentTime / 60)}:{(Math.floor(currentTime % 60) || 0).toString().padStart(2, '0')}
          </span>

          <input
            type="range"
            min="0"
            max={duration || 100}
            step="0.05"
            value={currentTime || 0}
            onChange={(e) => handleSeek(parseFloat(e.target.value))}
            className="flex-1 h-2 appearance-none bg-slate-800 rounded-full outline-none [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-amber-400 cursor-pointer"
          />

          <span className="text-xs font-mono text-slate-300 w-12">
            {Math.floor((duration || 0) / 60)}:{(Math.floor((duration || 0) % 60) || 0).toString().padStart(2, '0')}
          </span>
        </div>

        {/* Action Controls */}
        <div className="flex items-center justify-center gap-4">
          <button
            onClick={handleResetTimeline}
            title="Reset to 0:00"
            className="p-2 text-slate-400 hover:text-slate-200 bg-slate-800 hover:bg-slate-700 rounded-full transition cursor-pointer"
          >
            <RotateCcw size={16} />
          </button>

          <button
            onClick={togglePlayPause}
            disabled={!trackData?.lyrics || trackData.lyrics.length === 0}
            className="p-3.5 bg-amber-400 hover:bg-amber-300 disabled:bg-slate-800 disabled:text-slate-600 text-slate-950 rounded-full transition shadow-lg shadow-amber-400/25 active:scale-95 cursor-pointer flex items-center justify-center"
          >
            {isPlaying ? <Pause size={22} /> : <Play size={22} className="ml-0.5" fill="currentColor" />}
          </button>
        </div>
      </footer>

      {/* Modals */}
      <AutoGeneratorModal 
        isOpen={isAutoGrabOpen} 
        onClose={() => setIsAutoGrabOpen(false)} 
        onSongGenerated={handleSongAutoGenerated} 
        apiBaseUrl={apiBaseUrl} 
      />
      <StoryboardModal 
        trackData={trackData} 
        isOpen={isStoryboardOpen} 
        onClose={() => setIsStoryboardOpen(false)} 
        onStoryboardGenerated={(data) => setStoryboardData(data)} 
        apiBaseUrl={apiBaseUrl} 
      />
      <LyricsEditorModal 
        trackData={trackData} 
        isOpen={isEditorOpen} 
        onClose={() => setIsEditorOpen(false)} 
        onSaveLyrics={handleSaveFormattedLyrics} 
        apiBaseUrl={apiBaseUrl} 
      />
    </div>
  );
};

export default LyricsEnginePlayer;
